### ISSUE TITLE
Error related to 'payable' keyword

### ISSUE THREAD

**Issue by coinop-logan** [cmditch/elm-ethereum-generator#16]
I get this error

`Error in $[0]: When parsing the record constructor of type Types.Declaration the key payable was not present.`

when trying to generate a binding from the included ABI. (contract source included)

[smokesig.zip](https://github.com/cmditch/elm-ethereum-generator/files/4398649/smokesig.zip)

**Comment by cmditch** [comment]
Good to know. I'll have update the ABI parser to be up to spec. Should be pretty easy, thanks for including the ABI!

**Comment by cmditch** [comment]
Alright, 4.0.0 is pushed up with a fix for this bug. Removed 'payable' and 'constant' from the parsing, which we didn't need anyways, and seem to have been removed in the new ABI spec.
